'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class English
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DataRecoveryGruen.English", GetType(English).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Step 1, choose drive: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property _1_choose_drive() As String
            Get
                Return ResourceManager.GetString("1_choose_drive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stop ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property _stop() As String
            Get
                Return ResourceManager.GetString("stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bad ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property bad() As String
            Get
                Return ResourceManager.GetString("bad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bin ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property bin() As String
            Get
                Return ResourceManager.GetString("bin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Change language ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property change_language() As String
            Get
                Return ResourceManager.GetString("change_language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Current drive: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property current_drive() As String
            Get
                Return ResourceManager.GetString("current_drive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Data ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property data() As String
            Get
                Return ResourceManager.GetString("data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Documents ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property document() As String
            Get
                Return ResourceManager.GetString("document", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drive Information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property drive_information() As String
            Get
                Return ResourceManager.GetString("drive_information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drive Name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property drive_name() As String
            Get
                Return ResourceManager.GetString("drive_name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die drive information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property driveInfo() As String
            Get
                Return ResourceManager.GetString("driveInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ending ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Ending() As String
            Get
                Return ResourceManager.GetString("Ending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Estimated File Integrity ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Estimated_File_Integrity() As String
            Get
                Return ResourceManager.GetString("Estimated_File_Integrity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Excellent ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property excellent() As String
            Get
                Return ResourceManager.GetString("excellent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die file ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property file() As String
            Get
                Return ResourceManager.GetString("file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die File Name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property File_Name() As String
            Get
                Return ResourceManager.GetString("File_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die File Path ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property File_Path() As String
            Get
                Return ResourceManager.GetString("File_Path", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property filter() As String
            Get
                Return ResourceManager.GetString("filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fixed ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property fixed() As String
            Get
                Return ResourceManager.GetString("fixed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Format ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Format() As String
            Get
                Return ResourceManager.GetString("Format", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Get Help ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property getHelp() As String
            Get
                Return ResourceManager.GetString("getHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Good ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property good() As String
            Get
                Return ResourceManager.GetString("good", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hello ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Hello() As String
            Get
                Return ResourceManager.GetString("Hello", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die help ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property help() As String
            Get
                Return ResourceManager.GetString("help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property home() As String
            Get
                Return ResourceManager.GetString("home", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Horrible ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property horrible() As String
            Get
                Return ResourceManager.GetString("horrible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die info ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property info() As String
            Get
                Return ResourceManager.GetString("info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Label ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property label() As String
            Get
                Return ResourceManager.GetString("label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property language() As String
            Get
                Return ResourceManager.GetString("language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die MFT Sector Adress ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MFT_Sector_Adress() As String
            Get
                Return ResourceManager.GetString("MFT_Sector_Adress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Music ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property music() As String
            Get
                Return ResourceManager.GetString("music", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You can not change the Language while scanning ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property no_language_change_while_scan() As String
            Get
                Return ResourceManager.GetString("no_language_change_while_scan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ok() As String
            Get
                Return ResourceManager.GetString("ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property options() As String
            Get
                Return ResourceManager.GetString("options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Overwritten ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property overwritten() As String
            Get
                Return ResourceManager.GetString("overwritten", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Computer information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property pc_information() As String
            Get
                Return ResourceManager.GetString("pc_information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Pictures ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property picture() As String
            Get
                Return ResourceManager.GetString("picture", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Print and Export ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property print_export() As String
            Get
                Return ResourceManager.GetString("print_export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Print Preview ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property print_preview() As String
            Get
                Return ResourceManager.GetString("print_preview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Programs ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property program() As String
            Get
                Return ResourceManager.GetString("program", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Records ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property records() As String
            Get
                Return ResourceManager.GetString("records", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Recover ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property recover() As String
            Get
                Return ResourceManager.GetString("recover", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You can not recover to the same drive! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property recover_same_drive() As String
            Get
                Return ResourceManager.GetString("recover_same_drive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property refresh() As String
            Get
                Return ResourceManager.GetString("refresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Removable ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property removable() As String
            Get
                Return ResourceManager.GetString("removable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reset Filter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property reset_filter() As String
            Get
                Return ResourceManager.GetString("reset_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Scan ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property scan() As String
            Get
                Return ResourceManager.GetString("scan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Scan control ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property scan_control() As String
            Get
                Return ResourceManager.GetString("scan_control", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Scan for information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property scan_for_information() As String
            Get
                Return ResourceManager.GetString("scan_for_information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Scan results will be lost ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property scan_results_lost() As String
            Get
                Return ResourceManager.GetString("scan_results_lost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The scan has been stopped ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property scan_stop() As String
            Get
                Return ResourceManager.GetString("scan_stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Scanning File ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property scanning_file() As String
            Get
                Return ResourceManager.GetString("scanning_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Scanning in Progress ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property scanning_progress() As String
            Get
                Return ResourceManager.GetString("scanning_progress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Filter Format ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property select_filter() As String
            Get
                Return ResourceManager.GetString("select_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Send drive data with request ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property send_drive_information() As String
            Get
                Return ResourceManager.GetString("send_drive_information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Set language ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property set_language() As String
            Get
                Return ResourceManager.GetString("set_language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Set language to ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property set_language_to() As String
            Get
                Return ResourceManager.GetString("set_language_to", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property settings() As String
            Get
                Return ResourceManager.GetString("settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Size ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property size() As String
            Get
                Return ResourceManager.GetString("size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Text ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property text() As String
            Get
                Return ResourceManager.GetString("text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property type() As String
            Get
                Return ResourceManager.GetString("type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You still have a filter selected! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property u_still_have_filter_selected() As String
            Get
                Return ResourceManager.GetString("u_still_have_filter_selected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property unknown() As String
            Get
                Return ResourceManager.GetString("unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Videos ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property video() As String
            Get
                Return ResourceManager.GetString("video", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please wait ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property wait() As String
            Get
                Return ResourceManager.GetString("wait", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
