'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class German
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DataRecoveryGruen.German", GetType(German).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Schritt 1, wähle ein Laufwerk: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property _1_choose_drive() As String
            Get
                Return ResourceManager.GetString("1_choose_drive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stop ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property _stop() As String
            Get
                Return ResourceManager.GetString("stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Schlecht ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property bad() As String
            Get
                Return ResourceManager.GetString("bad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Papierkorb ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property bin() As String
            Get
                Return ResourceManager.GetString("bin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ändere Sprache ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property change_language() As String
            Get
                Return ResourceManager.GetString("change_language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aktuelles Laufwerk: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property current_drive() As String
            Get
                Return ResourceManager.GetString("current_drive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Daten ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property data() As String
            Get
                Return ResourceManager.GetString("data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dokument ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property document() As String
            Get
                Return ResourceManager.GetString("document", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Laufwerksinformationen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property drive_information() As String
            Get
                Return ResourceManager.GetString("drive_information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Laufwerk Name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property drive_name() As String
            Get
                Return ResourceManager.GetString("drive_name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Laufwerk Informationen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property driveInfo() As String
            Get
                Return ResourceManager.GetString("driveInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Endung ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Ending() As String
            Get
                Return ResourceManager.GetString("Ending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wiederherstellungswahrscheinlichkeit ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Estimated_File_Integrity() As String
            Get
                Return ResourceManager.GetString("Estimated_File_Integrity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ausgezeichnet ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property excellent() As String
            Get
                Return ResourceManager.GetString("excellent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datei ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property file() As String
            Get
                Return ResourceManager.GetString("file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datei Name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property File_Name() As String
            Get
                Return ResourceManager.GetString("File_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Datei Ort ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property File_Path() As String
            Get
                Return ResourceManager.GetString("File_Path", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property filter() As String
            Get
                Return ResourceManager.GetString("filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Eingebaut ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property fixed() As String
            Get
                Return ResourceManager.GetString("fixed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Format ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Format() As String
            Get
                Return ResourceManager.GetString("Format", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Professionelle Datenrettung anfragen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property getHelp() As String
            Get
                Return ResourceManager.GetString("getHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Gut ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property good() As String
            Get
                Return ResourceManager.GetString("good", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hallo ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Hello() As String
            Get
                Return ResourceManager.GetString("Hello", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property help() As String
            Get
                Return ResourceManager.GetString("help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property home() As String
            Get
                Return ResourceManager.GetString("home", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sehr-schlecht ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property horrible() As String
            Get
                Return ResourceManager.GetString("horrible", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property info() As String
            Get
                Return ResourceManager.GetString("info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bezeichnung ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property label() As String
            Get
                Return ResourceManager.GetString("label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property language() As String
            Get
                Return ResourceManager.GetString("language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die MFT Sektor Adresse ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MFT_Sector_Adress() As String
            Get
                Return ResourceManager.GetString("MFT_Sector_Adress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Musik ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property music() As String
            Get
                Return ResourceManager.GetString("music", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sie können die Sprache wärend eines scannes nicht ändern ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property no_language_change_while_scan() As String
            Get
                Return ResourceManager.GetString("no_language_change_while_scan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ok() As String
            Get
                Return ResourceManager.GetString("ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Optionen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property options() As String
            Get
                Return ResourceManager.GetString("options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Überschrieben ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property overwritten() As String
            Get
                Return ResourceManager.GetString("overwritten", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Computerinformation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property pc_information() As String
            Get
                Return ResourceManager.GetString("pc_information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bilder ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property picture() As String
            Get
                Return ResourceManager.GetString("picture", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Drucken und Exportieren ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property print_export() As String
            Get
                Return ResourceManager.GetString("print_export", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Druck Vorschau ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property print_preview() As String
            Get
                Return ResourceManager.GetString("print_preview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Programme ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property program() As String
            Get
                Return ResourceManager.GetString("program", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einträge ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property records() As String
            Get
                Return ResourceManager.GetString("records", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wiederherstellen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property recover() As String
            Get
                Return ResourceManager.GetString("recover", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Du kannst nicht auf die Selbe Festplatte recovern! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property recover_same_drive() As String
            Get
                Return ResourceManager.GetString("recover_same_drive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Aktualisieren ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property refresh() As String
            Get
                Return ResourceManager.GetString("refresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Extern ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property removable() As String
            Get
                Return ResourceManager.GetString("removable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Filter zurücksetzen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property reset_filter() As String
            Get
                Return ResourceManager.GetString("reset_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Scannen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property scan() As String
            Get
                Return ResourceManager.GetString("scan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Scan Kontrolle ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property scan_control() As String
            Get
                Return ResourceManager.GetString("scan_control", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Scanne für Informationen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property scan_for_information() As String
            Get
                Return ResourceManager.GetString("scan_for_information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Scanergebnisse gehen verloren ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property scan_results_lost() As String
            Get
                Return ResourceManager.GetString("scan_results_lost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Der Scan wurde gestoppt ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property scan_stop() As String
            Get
                Return ResourceManager.GetString("scan_stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Scanne Dateien ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property scanning_file() As String
            Get
                Return ResourceManager.GetString("scanning_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wird gescannt ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property scanning_progress() As String
            Get
                Return ResourceManager.GetString("scanning_progress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Filter auswählen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property select_filter() As String
            Get
                Return ResourceManager.GetString("select_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Laufwerkdaten bei Anfrage mitsenden ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property send_drive_information() As String
            Get
                Return ResourceManager.GetString("send_drive_information", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Setze Sprache ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property set_language() As String
            Get
                Return ResourceManager.GetString("set_language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Setze Sprache auf ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property set_language_to() As String
            Get
                Return ResourceManager.GetString("set_language_to", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property settings() As String
            Get
                Return ResourceManager.GetString("settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Größen ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property size() As String
            Get
                Return ResourceManager.GetString("size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Text ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property text() As String
            Get
                Return ResourceManager.GetString("text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Typ ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property type() As String
            Get
                Return ResourceManager.GetString("type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Du hast noch einen Filter ausgewählt! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property u_still_have_filter_selected() As String
            Get
                Return ResourceManager.GetString("u_still_have_filter_selected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unbekannt ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property unknown() As String
            Get
                Return ResourceManager.GetString("unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Video ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property video() As String
            Get
                Return ResourceManager.GetString("video", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bitte warten... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property wait() As String
            Get
                Return ResourceManager.GetString("wait", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
