'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DataRecoveryGruen.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;root&gt;
        '''  &lt;!-- 
        '''    Microsoft ResX Schema 
        '''    
        '''    Version 2.0
        '''    
        '''    The primary goals of this format is to allow a simple XML format 
        '''    that is mostly human readable. The generation and parsing of the 
        '''    various data types are done through the TypeConverter classes 
        '''    associated with the data types.
        '''    
        '''    Example:
        '''    
        '''    ... ado.net/XML headers &amp; schema ...
        '''    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        '''    &lt;resheader n [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property English() As String
            Get
                Return ResourceManager.GetString("English", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &apos;------------------------------------------------------------------------------
        '''&apos; &lt;auto-generated&gt;
        '''&apos;     Dieser Code wurde von einem Tool generiert.
        '''&apos;     Laufzeitversion:4.0.30319.42000
        '''&apos;
        '''&apos;     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
        '''&apos;     der Code erneut generiert wird.
        '''&apos; &lt;/auto-generated&gt;
        '''&apos;------------------------------------------------------------------------------
        '''
        '''Option Strict On
        '''Option Explicit On
        '''
        '''Imports System
        '''
        '''Namespace My.Resourc [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property English_Designer() As String
            Get
                Return ResourceManager.GetString("English_Designer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property favicon_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("favicon-32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;root&gt;
        '''  &lt;!-- 
        '''    Microsoft ResX Schema 
        '''    
        '''    Version 2.0
        '''    
        '''    The primary goals of this format is to allow a simple XML format 
        '''    that is mostly human readable. The generation and parsing of the 
        '''    various data types are done through the TypeConverter classes 
        '''    associated with the data types.
        '''    
        '''    Example:
        '''    
        '''    ... ado.net/XML headers &amp; schema ...
        '''    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        '''    &lt;resheader n [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property German() As String
            Get
                Return ResourceManager.GetString("German", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &apos;------------------------------------------------------------------------------
        '''&apos; &lt;auto-generated&gt;
        '''&apos;     Dieser Code wurde von einem Tool generiert.
        '''&apos;     Laufzeitversion:4.0.30319.42000
        '''&apos;
        '''&apos;     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
        '''&apos;     der Code erneut generiert wird.
        '''&apos; &lt;/auto-generated&gt;
        '''&apos;------------------------------------------------------------------------------
        '''
        '''Option Strict On
        '''Option Explicit On
        '''
        '''Imports System
        '''
        '''Namespace My.Resourc [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property German_Designer() As String
            Get
                Return ResourceManager.GetString("German_Designer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_autorenew_black_48dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_autorenew_black_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_delete_black_48dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_delete_black_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_find_in_page_black_48dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_find_in_page_black_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_get_app_black_48dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_get_app_black_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_highlight_off_black_48dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_highlight_off_black_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_history_black_48dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_history_black_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_live_help_black_48dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_live_help_black_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_print_black_48dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_print_black_48dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        '''</summary>
        Friend ReadOnly Property Manual_german() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Manual_german", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
